version: "2"

services:
    web:
        volumes:
            - ~/.composer/auth.json:/var/www/composer/auth.json
        environment:
            VIRTUAL_HOST: nolimits.docker
        extra_hosts:
            - dockerhost:$DOCKERHOST
        links:
            - db
            - blackfire
            - mail

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    mail:
        image: mailhog/mailhog:latest
        environment:
            VIRTUAL_HOST: mail.nolimits.docker
            VIRTUAL_PORT: 8025

    db:
        ports:
            - 13306:3306
