version: "2"

services:
    web:
        image: quay.io/thepixeldeveloper/nolimits-exchange-web
        volumes:
            - ~/.composer/auth.json:/var/www/composer/auth.json
            - ./projects/website:/var/www/nolimits
        links:
            - db
        extra_hosts:
            - "dockerhost:$DOCKERHOST"
        environment:
            VIRTUAL_HOST: "nolimits.docker"

    blackfire:
        image: blackfire/blackfire
        environment:
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN

    db:
        image: mysql:latest
        ports:
            - "13306:3306"
        volumes:
            - ./resources/db/base.sql:/docker-entrypoint-initdb.d/base.sql
        environment:
            MYSQL_ROOT_PASSWORD: "nolimits"
            MYSQL_DATABASE: "nolimits"
            MYSQL_USER: "nolimits"
            MYSQL_PASSWORD: "nolimits"
