imports:
    - { resource: config.yml }

framework:
    assets:
        packages:
            screenshots:
                base_url: "https://%object_storage_host%/images"

doctrine:
    orm:
        metadata_cache_driver:
            type: apcu
        query_cache_driver:
            type: apcu
        result_cache_driver:
            type: apcu
        second_level_cache:
            region_cache_driver:
                type: apcu

monolog:
    handlers:
        mail:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [error_log, deduplicated]
        error_log:
            type: error_log
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'error@nolimits-exchange.com'
            to_email:   'thepixeldeveloper@googlemail.com'
            subject:    'An Error Occurred! %%message%%'
            level:      debug
            formatter:  monolog.formatter.html
            content_type: text/html
