services:

    app.doctrine.rating_cache_listener:
      class: Thepixeldeveloper\Nolimitsexchange\AppBundle\EventListeners\RatingCacheListener
      tags:
          - { name: doctrine.event_listener, event: postPersist }

    app.doctrine.download_cache_listener:
      class: Thepixeldeveloper\Nolimitsexchange\AppBundle\EventListeners\DownloadCacheListener
      tags:
          - { name: doctrine.event_listener, event: postPersist }

    app.file_uploader:
        class: Thepixeldeveloper\Nolimitsexchange\AppBundle\Services\FileUploader
        arguments:
            - "%object_storage_tmp%/ephemeral"

    fos_user.user_provider.email:
        class: Thepixeldeveloper\Nolimitsexchange\AppBundle\Security\EmailProvider
        public: false
        arguments:
            - "@fos_user.user_manager"

    app.screenshot_extension:
        class: Thepixeldeveloper\Nolimitsexchange\AppBundle\Twig\ScreenshotExtension
        public: false
        arguments:
            - "@util.screenshot"
        tags:
            - { name: twig.extension }

    app.text_extension:
        class: Twig_Extensions_Extension_Text
        public: false
        tags:
            - { name: twig.extension }

    app.date_extension:
        class: Twig_Extensions_Extension_Date
        public: false
        tags:
            - { name: twig.extension }

    app.password_resetting:
        class: Thepixeldeveloper\Nolimitsexchange\AppBundle\EventListeners\PasswordResettingListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    flysystem.s3_client:
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, factory]
        arguments:
            -
                credentials:
                    key:    "%env(OBJECT_STORAGE_KEY)%"
                    secret: "%env(OBJECT_STORAGE_SECRET)%"
                version:  "latest"
                region:   "%env(OBJECT_STORAGE_REGION)%"
                endpoint: "https://%env(OBJECT_STORAGE_SERVER)%"
