imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~

services:

    listener.coaster.upload.started.add_to_queue:
        class: Thepixeldeveloper\Nolimitsexchange\AppBundle\EventListeners\Coaster\Upload\Started\AddToQueueListener
        arguments:
            - "@jobqueue"
        tags:
            - { name: kernel.event_listener, event: coaster.upload.started, priority: -255 }
